function Build-ServerLaunchCommand {
    param(
        [string]$InstallPath,
        [string]$GameMode,
        [string]$Map,
        [int]$Port = 27015
    )

    $srcdsPath = Join-Path $InstallPath "srcds.exe"

    if (-not (Test-Path $srcdsPath)) {
        Write-Log "srcds.exe not found at: $srcdsPath" "ERROR"
        return $null
    }

    $cmdArgs = @(
        "-console",
        "-game left4dead2",
        "-server",
        "-nohltv",
        "+sv_lan 0",
        "+sv_pure 1",
        "+exec server.cfg",
        "+map $Map"
    )

    if ($GameMode) {
        $cmdArgs += "+mp_gamemode $GameMode"
    }

    if ($Port -gt 0) {
        $cmdArgs += "-port $Port"
    }

    return @{
        Executable = $srcdsPath
        Arguments  = $cmdArgs -join " "
        Map        = $Map
        GameMode   = $GameMode
        Port       = $Port
    }
}

function Get-ServerLaunchBatch {
    param(
        [string]$InstallPath,
        [string]$GameMode,
        [string]$Map,
        [int]$Port = 27015,
        [string]$OutputPath
    )

    $cmd = Build-ServerLaunchCommand -InstallPath $InstallPath -GameMode $GameMode -Map $Map -Port $Port

    if (-not $cmd) {
        return $false
    }

    $serverDir = Split-Path $cmd.Executable -Parent
    $batchContent = @"
@echo off
REM Generated by L4D2 Dedicated Server Manager
REM GameMode: $GameMode
REM Map: $Map
REM Port: $Port

cd /d "$serverDir"

"$($cmd.Executable)" $($cmd.Arguments)

pause
"@

    Set-Content -Path $OutputPath -Value $batchContent -Encoding ASCII
    Write-Log "Launch batch created: $OutputPath" "INFO"
    return $true
}

Export-ModuleMember -Function Build-ServerLaunchCommand, Get-ServerLaunchBatch
